# Generated by Django 5.1.5 on 2025-02-10 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_first_name', models.CharField(max_length=50)),
                ('l_last_name', models.CharField(max_length=50)),
                ('l_email', models.EmailField(max_length=254, unique=True)),
                ('l_phone', models.CharField(max_length=15)),
                ('l_department', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ENG', 'Engineering'), ('BIZ', 'Business'), ('SCI', 'Science')], default='CS', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_reg_number', models.CharField(max_length=10, unique=True)),
                ('s_first_name', models.CharField(max_length=50)),
                ('s_last_name', models.CharField(max_length=50)),
                ('s_email', models.EmailField(max_length=254, unique=True)),
                ('s_phone', models.CharField(max_length=15)),
                ('s_Year', models.IntegerField(null=True)),
                ('s_department', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ENG', 'Engineering'), ('BIZ', 'Business'), ('SCI', 'Science')], default='CS', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lab')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lecture')),
                ('students', models.ManyToManyField(blank=True, to='app.students')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students')),
            ],
        ),
    ]
