# Generated by Django 5.1.5 on 2025-02-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='l_reg_number',
            field=models.CharField(default='RJT/0000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='s_reg_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
