# Generated by Django 5.1.5 on 2025-02-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lecture_l_reg_number_alter_students_s_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='s_Year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='s_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
