# Generated by Django 5.1.5 on 2025-02-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_classschedule_s_year_classschedule_s_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rescheduled', 'Rescheduled'), ('Finished', 'Finished')], default='Pending', max_length=20),
        ),
    ]
