# Generated by Django 5.1.5 on 2025-02-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_classschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='class_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
