# Generated by Django 5.1.5 on 2025-02-13 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_classschedule_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attendance_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classschedule')),
            ],
        ),
    ]
